# Generated by Django 5.2.1 on 2025-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('crew_member', 'document_name', 'document_type', 'document_no')},
        ),
    ]
