# Generated by Django 5.2.1 on 2025-06-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_management', '0002_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to the corresponding user account for login (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
