# Generated by Django 5.2.1 on 2025-06-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_management', '0003_crewmember_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewmember',
            options={},
        ),
        migrations.RemoveField(
            model_name='crewmember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crewmember',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='ExperienceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_principal_name', models.CharField(max_length=255, verbose_name='Company/Principal Name')),
                ('vessel_name', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(max_length=100)),
                ('payscale_wages', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payscale/Wages (Optional for Other Co.)')),
                ('port_of_joining', models.CharField(max_length=100)),
                ('sign_on_date', models.DateField()),
                ('sign_off_date', models.DateField()),
                ('port_of_sign_off', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_history', to='crew_management.crewmember')),
            ],
            options={
                'verbose_name': 'Crew Member',
                'verbose_name_plural': 'Crew Members',
            },
        ),
    ]
