# Generated by Django 5.2.1 on 2025-06-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_management', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('PASSWORD_CHANGE', 'Password Changed'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('IMPORT', 'Data Imported'), ('EXPORT', 'Data Exported'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_FAIL', 'Email Failed')], max_length=50),
        ),
        migrations.CreateModel(
            name='FinancialObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('RETIREMENT_DUE', 'Retirement Due'), ('LOAN', 'Loan'), ('FINE', 'Fine'), ('BONUS', 'Bonus'), ('OTHER', 'Other Obligation')], max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Any balance transferred from previous records.', max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid against this obligation.', max_digits=10)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='OUTSTANDING', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('ssb_cdc_numbers', models.JSONField(blank=True, help_text='List of SSB/CDC numbers (JSON format: [{"number": "value", "expiry": "YYYY-MM-DD"}])', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_vessel', models.ForeignKey(blank=True, help_text="Vessel or contract period this obligation is tied to (e.g., Gratuity from this vessel's tenure).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew_management.vessel', verbose_name='Associated Vessel/Contract')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_obligations', to='crew_management.crewmember')),
            ],
            options={
                'verbose_name': 'Financial Obligation',
                'verbose_name_plural': 'Financial Obligations',
                'ordering': ['due_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotment_month', models.DateField(help_text='Month and year for this allotment (e.g., 2025-06-01)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('funding_from_principal_status', models.CharField(choices=[('RECEIVED', 'Received'), ('NOT_RECEIVED', 'Not Received'), ('PRINCIPAL_PAYS_DIRECT', 'Principal Pays Direct')], default='NOT_RECEIVED', help_text='Status of funds from Principal for this allotment.', max_length=30)),
                ('tentative_payment_date', models.DateField(help_text='Tentative date for payment to crew. Used for alerts.')),
                ('actual_payment_date', models.DateField(blank=True, help_text='Actual date payment was confirmed to crew.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial Payment'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('transaction_reference', models.CharField(blank=True, help_text='Internal transaction ID or bank reference.', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_allotments', to='crew_management.crewmember')),
                ('vessel', models.ForeignKey(blank=True, help_text='Vessel crew member was onboard during this allotment period.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew_management.vessel', verbose_name='Vessel at Allotment')),
            ],
            options={
                'verbose_name': 'Monthly Allotment',
                'verbose_name_plural': 'Monthly Allotments',
                'ordering': ['-allotment_month'],
                'unique_together': {('crew_member', 'allotment_month')},
            },
        ),
    ]
